### ISSUE TITLE
Being shown unknown error

### ISSUE THREAD

**Issue by chris-burrow-apps** [troykelly/hacs-trackimo#3]
I am being shown "Unknown error" within home assistant ui. Looking at the logs it returns with:

`Traceback (most recent call last):
  File "/config/custom_components/trackimo/config_flow.py", line 68, in async_step_user
    info = await validate_input(self.hass, user_input)

  File "/config/custom_components/trackimo/config_flow.py", line 33, in validate_input
    if not await api.login(data["username"], data["password"]):

  File "/usr/local/lib/python3.12/site-packages/trackimo/API/main.py", line 60, in login
    authData = await self.__protocol.login()

  File "/usr/local/lib/python3.12/site-packages/trackimo/protocol/protocol.py", line 187, in login
    raise TrackimoLoginFailed(
trackimo.exceptions.TrackimoLoginFailed`

I tried logging into the app using the same details I gave the integration and it was successful.

![Screenshot 2024-04-28 225944](https://github.com/troykelly/hacs-trackimo/assets/5174337/8604ffbb-3667-4365-8a9f-b406521f612a)

![Screenshot 2024-04-28 225930](https://github.com/troykelly/hacs-trackimo/assets/5174337/09b0cace-ecc6-481e-92cd-582f37d3b78f)

**Comment by troykelly** [comment]
Closed - Life360 API access issue.
https://github.com/troykelly/hacs-trackimo?tab=readme-ov-file#notice
